site_name: Wuttichai.K's Docs
# site_url: https://mydomain.org/mysite

# Repository
repo_name: wuttichai-hung/mydocs
repo_url: https://github.com/wuttichai-hung/mydocs

# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences